name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build on GitHub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Lint with Maven
      run: mvn checkstyle:checkstyle

    - name: Run unit tests
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml
