name: Manual Deployment to EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version to deploy'
        required: true

env:
  EKS_CLUSTER_NAME: Github-Action-Demo
  AWS_REGION: ap-northeast-1

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send workflow URL to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "A new deployment has been initiated! Approve it here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
  deploy:
    runs-on: ubuntu-latest
    environment: scolley31
    env:
      IMAGE_TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Update Kubernetes Configuration
        run: |
          sed -i "s|demo:v0.21|demo:${{ env.IMAGE_TAG }}|g" k8s.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s.yaml
