name: Manual Deployment to EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version to deploy'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send workflow URL to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "A new deployment has been initiated! Approve it here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
  deploy:
    runs-on: ubuntu-latest
    environment: scolley31
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
